# Generated by Django 2.2.8 on 2019-12-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('uuid', models.CharField(blank=True, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('modified', models.DateTimeField(blank=True)),
            ],
            options={
                'ordering': ['-modified'],
            },
        ),
    ]
