# Generated by Django 2.2.8 on 2019-12-29 20:48

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='title',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
