# Generated by Django 2.2.8 on 2019-12-29 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0002_note_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('uuid', models.CharField(blank=True, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('modified', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='note',
            name='starred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
