# Generated by Django 2.2.8 on 2019-12-29 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20191230_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='uuid',
        ),
        migrations.AddField(
            model_name='note',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
