# Generated by Django 2.2.8 on 2020-01-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_note_starred'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='raw_text',
            new_name='plain_text',
        ),
        migrations.AddField(
            model_name='note',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
