# Generated by Django 2.2.8 on 2020-01-08 04:39

from django.conf import settings
from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0004_auto_20200108_1528'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Note',
            new_name='Topic',
        ),
        migrations.AlterField(
            model_name='content',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
