# Generated by Django 2.2.8 on 2020-01-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_auto_20200108_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='starred',
            field=models.BooleanField(default=False),
        ),
    ]
